/**
 * Mock feed data for development/demo purposes.
 *
 * Provides realistic-looking GitHub repository cards so the frontend
 * can render without external dependencies (no DB, no GitHub API token).
 */

import type { RepoCard } from '@/lib/types';

function daysAgo(days: number): Date {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000);
}

/** Generate mock RepoCard data for development */
export function getMockRepoCards(): RepoCard[] {
  const cards: RepoCard[] = [
    {
      id: 'mock-react',
      fullName: 'facebook/react',
      owner: 'facebook',
      name: 'react',
      description: 'The library for web and native user interfaces.',
      language: 'JavaScript',
      starCount: 224000,
      forkCount: 45700,
      topics: ['javascript', 'frontend', 'ui', 'declarative', 'component'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'React is a JavaScript library for building user interfaces. It lets you compose complex UIs from small and isolated pieces of code called "components". React has been designed from the start for gradual adoption.',
      lastCommitAt: new Date('2024-12-01'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'mock-nextjs',
      fullName: 'vercel/next.js',
      owner: 'vercel',
      name: 'next.js',
      description: 'The React Framework for the Web.',
      language: 'JavaScript',
      starCount: 125000,
      forkCount: 26800,
      topics: ['react', 'nextjs', 'ssr', 'framework', 'fullstack'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Next.js is a React framework that gives you building blocks to create web applications. By framework, we mean Next.js handles the tooling and configuration needed for React, and provides additional structure and features.',
      lastCommitAt: new Date('2024-11-28'),
      defaultBranch: 'canary',
      updatedAt: new Date('2024-11-28'),
    },
    {
      id: 'mock-rust',
      fullName: 'rust-lang/rust',
      owner: 'rust-lang',
      name: 'rust',
      description: 'Empowering everyone to build reliable and efficient software.',
      language: 'Rust',
      starCount: 97000,
      forkCount: 12500,
      topics: ['rust', 'compiler', 'systems-programming', 'performance', 'safety'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Rust is a systems programming language focused on safety, speed, and concurrency. It accomplishes these goals by being memory safe without using garbage collection. Rust is syntactically similar to C++.',
      lastCommitAt: new Date('2024-12-02'),
      defaultBranch: 'master',
      updatedAt: new Date('2024-12-02'),
    },
    {
      id: 'mock-vscode',
      fullName: 'microsoft/vscode',
      owner: 'microsoft',
      name: 'vscode',
      description: 'Visual Studio Code - Open Source IDE.',
      language: 'TypeScript',
      starCount: 163000,
      forkCount: 28900,
      topics: ['editor', 'ide', 'typescript', 'electron', 'developer-tools'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux. It comes with built-in support for JavaScript, TypeScript and Node.js.',
      lastCommitAt: new Date('2024-12-01'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'mock-deno',
      fullName: 'denoland/deno',
      owner: 'denoland',
      name: 'deno',
      description: 'A modern runtime for JavaScript and TypeScript.',
      language: 'Rust',
      starCount: 94000,
      forkCount: 5200,
      topics: ['deno', 'typescript', 'runtime', 'javascript', 'v8'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Deno is a simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust. It ships a single executable with no dependencies and has built-in tooling like a formatter and linter.',
      lastCommitAt: new Date('2024-11-30'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-30'),
    },
    {
      id: 'mock-tailwindcss',
      fullName: 'tailwindlabs/tailwindcss',
      owner: 'tailwindlabs',
      name: 'tailwindcss',
      description: 'A utility-first CSS framework for rapid UI development.',
      language: 'JavaScript',
      starCount: 82000,
      forkCount: 4100,
      topics: ['css', 'tailwind', 'utility-first', 'responsive', 'design'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Tailwind CSS is a utility-first CSS framework packed with classes like flex, pt-4, text-center and rotate-90 that can be composed to build any design, directly in your markup.',
      lastCommitAt: new Date('2024-11-25'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-25'),
    },
    {
      id: 'mock-svelte',
      fullName: 'sveltejs/svelte',
      owner: 'sveltejs',
      name: 'svelte',
      description: 'Cybernetically enhanced web apps.',
      language: 'JavaScript',
      starCount: 79000,
      forkCount: 4100,
      topics: ['svelte', 'compiler', 'frontend', 'ui', 'reactive'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Svelte is a new approach to building user interfaces. Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app.',
      lastCommitAt: new Date('2024-11-29'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-29'),
    },
    {
      id: 'mock-pytorch',
      fullName: 'pytorch/pytorch',
      owner: 'pytorch',
      name: 'pytorch',
      description: 'Tensors and Dynamic neural networks in Python with strong GPU acceleration.',
      language: 'Python',
      starCount: 82000,
      forkCount: 22000,
      topics: ['python', 'deep-learning', 'machine-learning', 'neural-network', 'gpu'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'PyTorch is a Python package that provides tensor computation with strong GPU acceleration and deep neural networks built on a tape-based autograd system. It is primarily developed by Meta AI.',
      lastCommitAt: new Date('2024-12-01'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'mock-langchain',
      fullName: 'langchain-ai/langchain',
      owner: 'langchain-ai',
      name: 'langchain',
      description: 'Build context-aware reasoning applications.',
      language: 'Python',
      starCount: 93000,
      forkCount: 14800,
      topics: ['llm', 'ai', 'langchain', 'agents', 'rag'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'LangChain is a framework for developing applications powered by large language models (LLMs). It provides tools for building chains, agents, and retrieval-augmented generation (RAG) pipelines.',
      lastCommitAt: new Date('2024-12-02'),
      defaultBranch: 'master',
      updatedAt: new Date('2024-12-02'),
    },
    {
      id: 'mock-bun',
      fullName: 'oven-sh/bun',
      owner: 'oven-sh',
      name: 'bun',
      description: 'Incredibly fast JavaScript runtime, bundler, test runner, and package manager.',
      language: 'Zig',
      starCount: 73000,
      forkCount: 2700,
      topics: ['javascript', 'runtime', 'bundler', 'zig', 'performance'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Bun is an all-in-one JavaScript runtime and toolkit designed for speed, complete with a bundler, test runner, and Node.js-compatible package manager. It aims to be a drop-in replacement for Node.js.',
      lastCommitAt: new Date('2024-11-30'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-30'),
    },
    {
      id: 'mock-astro',
      fullName: 'withastro/astro',
      owner: 'withastro',
      name: 'astro',
      description: 'The web framework for content-driven websites.',
      language: 'TypeScript',
      starCount: 46000,
      forkCount: 2400,
      topics: ['astro', 'static-site', 'ssg', 'islands', 'performance'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Astro is the web framework for building content-driven websites like blogs, marketing, and e-commerce. Astro is best-known for pioneering a new frontend architecture to reduce JavaScript overhead.',
      lastCommitAt: new Date('2024-11-28'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-28'),
    },
    {
      id: 'mock-turbo',
      fullName: 'vercel/turbo',
      owner: 'vercel',
      name: 'turbo',
      description: 'Incremental bundler and build system optimized for JavaScript and TypeScript.',
      language: 'Rust',
      starCount: 26000,
      forkCount: 1800,
      topics: ['monorepo', 'build-system', 'turborepo', 'turbopack', 'rust'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Turbo is an incremental bundler and build system optimized for JavaScript and TypeScript, written in Rust. It includes Turborepo for monorepo management and Turbopack for fast bundling.',
      lastCommitAt: new Date('2024-11-27'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-27'),
    },
    {
      id: 'mock-drizzle',
      fullName: 'drizzle-team/drizzle-orm',
      owner: 'drizzle-team',
      name: 'drizzle-orm',
      description: 'Headless TypeScript ORM with a head.',
      language: 'TypeScript',
      starCount: 24000,
      forkCount: 580,
      topics: ['orm', 'typescript', 'sql', 'database', 'postgres'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Drizzle ORM is a headless TypeScript ORM. It looks and feels like writing SQL in TypeScript. It provides type-safe database access with zero dependencies and supports PostgreSQL, MySQL, and SQLite.',
      lastCommitAt: new Date('2024-11-29'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-29'),
    },
    {
      id: 'mock-shadcn-ui',
      fullName: 'shadcn-ui/ui',
      owner: 'shadcn-ui',
      name: 'ui',
      description: 'Beautifully designed components built with Radix UI and Tailwind CSS.',
      language: 'TypeScript',
      starCount: 72000,
      forkCount: 4200,
      topics: ['react', 'components', 'tailwind', 'radix', 'ui-library'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'A collection of re-usable components built using Radix UI and Tailwind CSS. This is NOT a component library. It is a collection of re-usable components that you can copy and paste into your apps.',
      lastCommitAt: new Date('2024-11-30'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-30'),
    },
    {
      id: 'mock-excalidraw',
      fullName: 'excalidraw/excalidraw',
      owner: 'excalidraw',
      name: 'excalidraw',
      description: 'Virtual whiteboard for sketching hand-drawn like diagrams.',
      language: 'TypeScript',
      starCount: 82000,
      forkCount: 7600,
      topics: ['drawing', 'whiteboard', 'collaboration', 'canvas', 'diagrams'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Excalidraw is a virtual collaborative whiteboard tool that lets you easily sketch diagrams that have a hand-drawn feel to them. It supports real-time collaboration and end-to-end encryption.',
      lastCommitAt: new Date('2024-11-28'),
      defaultBranch: 'master',
      updatedAt: new Date('2024-11-28'),
    },
    {
      id: 'mock-zod',
      fullName: 'colinhacks/zod',
      owner: 'colinhacks',
      name: 'zod',
      description: 'TypeScript-first schema validation with static type inference.',
      language: 'TypeScript',
      starCount: 33000,
      forkCount: 1100,
      topics: ['typescript', 'validation', 'schema', 'parsing', 'type-safety'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Zod is a TypeScript-first schema declaration and validation library. It eliminates duplicative type declarations. With Zod, you declare a validator once and Zod will automatically infer the static TypeScript type.',
      lastCommitAt: new Date('2024-11-20'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-20'),
    },
    {
      id: 'mock-hono',
      fullName: 'honojs/hono',
      owner: 'honojs',
      name: 'hono',
      description: 'Web framework built on Web Standards for Cloudflare Workers, Deno, Bun, and Node.js.',
      language: 'TypeScript',
      starCount: 19000,
      forkCount: 540,
      topics: ['web-framework', 'cloudflare', 'edge', 'typescript', 'fast'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Hono is a small, simple, and ultrafast web framework built on Web Standards. It works on any JavaScript runtime: Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, AWS Lambda, and Node.js.',
      lastCommitAt: new Date('2024-12-01'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'mock-ollama',
      fullName: 'ollama/ollama',
      owner: 'ollama',
      name: 'ollama',
      description: 'Get up and running with Llama 3, Mistral, Gemma, and other large language models.',
      language: 'Go',
      starCount: 98000,
      forkCount: 7800,
      topics: ['llm', 'ai', 'local', 'inference', 'golang'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Ollama allows you to run open-source large language models locally. It bundles model weights, configuration, and data into a single package, defined by a Modelfile. Supports Llama 3, Mistral, and more.',
      lastCommitAt: new Date('2024-12-02'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-12-02'),
    },
    {
      id: 'mock-tauri',
      fullName: 'tauri-apps/tauri',
      owner: 'tauri-apps',
      name: 'tauri',
      description: 'Build smaller, faster, and more secure desktop and mobile applications with a web frontend.',
      language: 'Rust',
      starCount: 83000,
      forkCount: 2500,
      topics: ['rust', 'desktop', 'webview', 'cross-platform', 'security'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Tauri is a framework for building tiny, fast binaries for all major desktop and mobile platforms. Developers can integrate any frontend framework that compiles to HTML, JS, and CSS for building their user interface.',
      lastCommitAt: new Date('2024-11-29'),
      defaultBranch: 'dev',
      updatedAt: new Date('2024-11-29'),
    },
    {
      id: 'mock-trpc',
      fullName: 'trpc/trpc',
      owner: 'trpc',
      name: 'trpc',
      description: 'Move Fast and Break Nothing. End-to-end typesafe APIs made easy.',
      language: 'TypeScript',
      starCount: 34000,
      forkCount: 1200,
      topics: ['typescript', 'api', 'rpc', 'type-safety', 'fullstack'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'tRPC allows you to easily build and consume fully typesafe APIs without schemas or code generation. It leverages TypeScript inference to provide end-to-end type safety between your client and server.',
      lastCommitAt: new Date('2024-11-26'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-11-26'),
    },
    {
      id: 'mock-biome',
      fullName: 'biomejs/biome',
      owner: 'biomejs',
      name: 'biome',
      description: 'A toolchain for web projects, aimed to provide functionalities to maintain them.',
      language: 'Rust',
      starCount: 15000,
      forkCount: 470,
      topics: ['linter', 'formatter', 'rust', 'javascript', 'toolchain'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Biome is a performant toolchain for web projects. It provides a fast formatter and linter for JavaScript, TypeScript, JSX, and JSON. Written in Rust for maximum performance.',
      lastCommitAt: new Date('2024-12-01'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-12-01'),
    },
    {
      id: 'mock-htmx',
      fullName: 'bigskysoftware/htmx',
      owner: 'bigskysoftware',
      name: 'htmx',
      description: 'High power tools for HTML.',
      language: 'JavaScript',
      starCount: 38000,
      forkCount: 1300,
      topics: ['html', 'hypermedia', 'ajax', 'websockets', 'simplicity'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'htmx gives you access to AJAX, CSS Transitions, WebSockets and Server Sent Events directly in HTML, using attributes, so you can build modern user interfaces with the simplicity and power of hypertext.',
      lastCommitAt: new Date('2024-11-25'),
      defaultBranch: 'master',
      updatedAt: new Date('2024-11-25'),
    },
    {
      id: 'mock-effect',
      fullName: 'Effect-TS/effect',
      owner: 'Effect-TS',
      name: 'effect',
      description: 'An ecosystem of tools for building production-grade TypeScript applications.',
      language: 'TypeScript',
      starCount: 7200,
      forkCount: 230,
      topics: ['typescript', 'functional-programming', 'effect-system', 'concurrency', 'schema'],
      isArchived: false,
      isFork: false,
      readmeSummary: 'Effect is a powerful TypeScript library designed to help developers easily create complex, synchronous, and asynchronous programs. It provides structured concurrency, error handling, and dependency injection.',
      lastCommitAt: new Date('2024-12-02'),
      defaultBranch: 'main',
      updatedAt: new Date('2024-12-02'),
    },
  ];

  return cards.map((card, index) => {
    const mockUpdatedAt = daysAgo(index === 0 ? 5 : (index % 14) + 1);

    return {
      ...card,
      lastCommitAt: mockUpdatedAt,
      updatedAt: mockUpdatedAt,
    };
  });
}

/**
 * Get a paginated slice of mock feed data.
 * Simulates cursor-based pagination over the mock dataset.
 */
export function getMockFeedResponse(cursor?: string, limit: number = 10) {
  const allCards = getMockRepoCards();
  let offset = 0;

  if (cursor) {
    try {
      const parsed = JSON.parse(cursor) as { offset: number };
      if (typeof parsed.offset === 'number' && parsed.offset >= 0) {
        offset = parsed.offset;
      }
    } catch {
      // Invalid cursor, start from beginning
    }
  }

  const cards = allCards.slice(offset, offset + limit);
  const hasMore = offset + limit < allCards.length;
  const nextCursor = hasMore
    ? JSON.stringify({ offset: offset + limit })
    : null;

  return {
    cards,
    nextCursor,
    hasMore,
  };
}
